// <auto-generated />
namespace FlashCards.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AspNetUsersSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AspNetUsersSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201701272316066_AspNetUsersSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
